Arguments: 
  /usr/local/Cellar/node/11.1.0/bin/node /Users/z002rgr/.yarn/bin/yarn.js add -

PATH: 
  /Users/z002rgr/.yarn/bin:/Users/z002rgr/.config/yarn/global/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin:/usr/local/Cellar/postgresql@9.6/9.6.10/bin:/Users/z002rgr/Tools/gardenia:/Users/z002rgr/Tools/kafka/kafka_2.12-0.11.0.3/bin

Yarn version: 
  1.12.3

Node version: 
  11.1.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/-: Not found
      at Request.params.callback [as _callback] (/Users/z002rgr/.yarn/lib/cli.js:65894:18)
      at Request.self.callback (/Users/z002rgr/.yarn/lib/cli.js:129018:22)
      at Request.emit (events.js:182:13)
      at Request.<anonymous> (/Users/z002rgr/.yarn/lib/cli.js:129990:10)
      at Request.emit (events.js:182:13)
      at IncomingMessage.<anonymous> (/Users/z002rgr/.yarn/lib/cli.js:129912:12)
      at Object.onceWrapper (events.js:273:13)
      at IncomingMessage.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1094:12)
      at process.internalTickCallback (internal/process/next_tick.js:72:19)

npm manifest: 
  {
    "name": "provict",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "devDependencies": {
      "@types/node": "^10.12.10"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  
  "@types/node@^10.12.10":
    version "10.12.10"
    resolved "https://registry.yarnpkg.com/@types/node/-/node-10.12.10.tgz#4fa76e6598b7de3f0cb6ec3abacc4f59e5b3a2ce"
    integrity sha512-8xZEYckCbUVgK8Eg7lf5Iy4COKJ5uXlnIOnePN0WUwSQggy9tolM+tDJf7wMOnT/JT/W9xDYIaYggt3mRV2O5w==
